/* eslint-env node */
"use strict";

const js = require("@eslint/js");

module.exports = [
  js.configs.recommended,
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.git/**",
      "**/frontend/dist/**",
      "**/backend/data/**",
    ],
  },
  {
    files: [
      "backend/**/*.js",
      "frontend/src/**/*.js",
      "frontend/src/**/*.jsx",
      "frontend/src/**/*.ts",
      "frontend/src/**/*.tsx",
      "scripts/**/*.js",
      "scripts/**/*.mjs",
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        process: "readonly",
        console: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "writable",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setImmediate: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        screen: "readonly",
        requestAnimationFrame: "readonly",
        sessionStorage: "readonly",
        localStorage: "readonly",
        history: "readonly",
        location: "readonly",
        global: "readonly",
        URLSearchParams: "readonly",
        CustomEvent: "readonly",
        Image: "readonly",
        HTMLElement: "readonly",
        NodeList: "readonly",
        Element: "readonly",
        Event: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        AbortController: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        URL: "readonly",
        crypto: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "prefer-const": "warn",
    },
  },
];
